export const userConstants = {
    USER_LOGIN: "USER_LOGIN",
    USER_LOGOUT: "USER_LOGOUT",
    USER_UPDATE_ALBUM: "USER_UPDATE_ALBUM",
    USER_UPDATE_ONE_ALBUM: "USER_UPDATE_ONE_ALBUM",
    USER_UNSHARE_ALBUM_WITH_ME: "USER_UNSHARE_ALBUM_WITH_ME",
    USER_UNSHARE_IMAGE_WITH_ME: "USER_UNSHARE_IMAGE_WITH_ME"
}